services:
  latex-app:
    build: ./frontend
    ports:
      - "7474:7474"
    container_name: latex-app
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=7474
    volumes:
      - ./logs:/app/logs
      - ./images:/app/images
